trigger:
  branches:
    exclude:
      - '*'

pr:
- '*'
# Runs every hour at the beginning of the hour

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18'


  - script: |
      echo "Hello"
      cd wdio_2
      chmod +x ./node_modules/.bin/wdio
      npm install selenium-webdriver 
      npm install webdriverio
      npm i
      npm install
      npm run single
    displayName: 'Run Tests'
